version: '3.8'

services:
  frontend:
    build:
      context: ./app-ies-claudiomaza-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./app-ies-claudiomaza-backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./app-ies-claudiomaza-backend/db.json:/app/db.json
